// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqa-dwuZrwYzRleqrDO-p-Q6_VN6fNdE',
    appId: '1:331425930183:web:95fc54b6011d1a1ab1d7e2',
    messagingSenderId: '331425930183',
    projectId: 'fdsma-7g6jig',
    authDomain: 'fdsma-7g6jig.firebaseapp.com',
    storageBucket: 'fdsma-7g6jig.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActGAuM1MjS2cEPrF--V3NXkNgjJWt6cc',
    appId: '1:331425930183:android:a58dc2e8d56082c1b1d7e2',
    messagingSenderId: '331425930183',
    projectId: 'fdsma-7g6jig',
    storageBucket: 'fdsma-7g6jig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtfJTvC0D9Obj8xyefW_ipe9geEJJQWQ',
    appId: '1:331425930183:ios:dacb93505d929d7db1d7e2',
    messagingSenderId: '331425930183',
    projectId: 'fdsma-7g6jig',
    storageBucket: 'fdsma-7g6jig.appspot.com',
    iosBundleId: 'company.privateaero.fdsma.driver.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtfJTvC0D9Obj8xyefW_ipe9geEJJQWQ',
    appId: '1:331425930183:ios:255e93618071f0c1b1d7e2',
    messagingSenderId: '331425930183',
    projectId: 'fdsma-7g6jig',
    storageBucket: 'fdsma-7g6jig.appspot.com',
    iosBundleId: 'com.gotaxi.taxi.driverFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrqa-dwuZrwYzRleqrDO-p-Q6_VN6fNdE',
    appId: '1:331425930183:web:af895672f9b083fab1d7e2',
    messagingSenderId: '331425930183',
    projectId: 'fdsma-7g6jig',
    authDomain: 'fdsma-7g6jig.firebaseapp.com',
    storageBucket: 'fdsma-7g6jig.appspot.com',
  );

}